### ISSUE TITLE
Deb file returns a Trace/breakpoint trap error

### ISSUE THREAD

**Issue by Laporte12974** [Bambosh/unofficial-homestuck-collection#173]
I just downloaded the deb file, to install it on my computer, running Debian 10. The installation went without a hitch. However, running the program always returns a Trace/breakpoint trap. It was the exact same error when running the file extracted from the tar.gz archive. Any idea why it isn't working?

**Comment by amiaship** [comment]
Same issue here from both the deb file and the tar.gz, also running Debian 10. When I run the executable from the tar.gz, I get this error:

`~/downloads/targz-unofficial-homestuck-collection-1.1.0$ ./unofficial-homestuck-collection 
[2124:0828/105000.816453:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, > but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that ./chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap`

**Comment by amiaship** [comment]
Apparently this is a bug in Electron mishandling user permissions, not just in the collection. Found a workaround here by changing permissions as the error message asks:

> Also see here https://github.com/electron/electron/issues/16631#issuecomment-476082063 So to make suid sandbox work you basically have to tweak the `chrome-sandbox` binary this way:
> - `sudo chown root chrome-sandbox`
> - `chmod 4755 chrome-sandbox`
> 
> The issue is more severe though if running appimage/snap packages, I have not yet revealed a decent workaround for these cases. It's working if appimage is executed with `--no-sandbox` arguemnt, but this is a hack.

_Originally posted by @vladimiry in https://github.com/electron/electron/issues/17972#issuecomment-487369441_

**Comment by GiovanH** [comment]
@Laporte12974 Did this workaround resolve your issue?

**Comment by GiovanH** [comment]
Couldn't get followup info, closing
