### ISSUE TITLE
Asset pack: Incorrect file path in comics.json comment

### ISSUE THREAD

**Issue by SimonAfek** [Bambosh/unofficial-homestuck-collection#26]
I was poking through the asset pack and found the comment in `comics.json` about how more old Hussie comics can be added by downloading the MrCheeze archive and extracting them. The comment says to extract them to `[Asset Directory]/archive/tso`, though the actual correct path is `[Asset Directory]/archive/comics/tso`.

Incidentally, what's the reasoning behind not just including them to begin with? It doesn't seem like it adds much to the file size, compared to how big it already is.

**Comment by Bambosh** [comment]
Whoops! well, at least the kind of people who see it will be able to figure out the mistake.

In general, most omissions like this were deliberate. Archiving the older stuff was kind of an ethical nightmare, and deciding what was important enough to keep never had a clear answer. It's important to remember a lot of this stuff is comprised of weird doodles a guy was making for fun like 15 years ago, some of which he's actively trying to distance himself from. TSO in general made me feel like I was crossing a few lines, so I didn't want to include more than was necessary. I didn't want those comics to be super easy to access for inexperienced readers due to the problems it could have caused, but there isn't really anything I can do to prevent people from adding them on their own.
