### ISSUE TITLE
Trickster theme has two banners

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#29]
In the trickster mode pages, the Homestuck navigation bar at the top is supposed to be replaced entirely by the trickster navigation flash, but instead both bars are stacked on top of each other. 

A proposed way to fix this without creating an accessibility issue is to relocate the real navigation bar to the bottom of the page.

**Comment by Bambosh** [comment]
Not personally convinced this is an issue, but there are a few possible outcomes:
- Leave as is. Benefits include: less work
- Move the navbar to the bottom of the screen as suggested. These would be the only pages in the program to do so, which makes me weep for the spirit of UX design. Really not a fan of this.
- Hide the navbar entirely. This isnt _completely_ unprecedented, since the same is done on several fullscreen flash pages. I'm not sure how good of an idea it'd be to do this for the 60-ish pages the Trickster arc lasts. Would keep it consistent with the original site at least?
- Some alternate solution we haven't thought of yet. Maybe pop the navbar out while the user is hovering over the fruit banner?

**Comment by GiovanH** [comment]
Handled in oddities.
