### ISSUE TITLE
Page 1720 doesn't have the original musics when Controversial Content is enabled.

### ISSUE THREAD

**Issue by lKomus** [Bambosh/unofficial-homestuck-collection#342]
If you have Controversial Content enabled when you reach Page 1720, you will get this selection of music shown instead of the ones made by Bollin:

![The_Unofficial_Homestuck_Collection_qdaa2DwRHk](https://user-images.githubusercontent.com/4800879/155597044-a858b5e7-68bd-4a7d-b55c-6b0f4773596e.png)

The "shatterface" song doesn't have a link and I'm not sure if it's supposed to exist, the flash does play a different song compared to the "non-controversial" page.

Enabling Controversial Content directly on page 1720 does display the proper songs but the flash is unchanged. And if you reload the application, the selection goes back to what is shown on the screenshot.
However this only happens if these two conditions are met:
    * Enabling Controversial Content is initially on OFF.
    * You have never switched this option on ON or OFF on another page than 1720 either since the application launched or after a reload.

![The_Unofficial_Homestuck_Collection_UrXfOYwkVM](https://user-images.githubusercontent.com/4800879/155598023-f1159339-d043-4a7c-a2c1-ddf86ed24bea.png)

Since the original songs are shown, I assume that the expected behavior is that the songs made by Bollin are played when Enable Controversial Content is ON.

Using 2.05 with the Asset Pack v2 on Windows 10.

**Comment by Sixthhokage1** [comment]
This is a result of the "SolusLunes music" option overriding "Bill Bolin music" on this flash as noted in the granular controversial content options. Of course, with new reader mode active you can't access those granular options, it's all or nothing unless you enable controversial content then edit config.json to set `"soluslunes": false`.

To explain the different versions of Shut Up And Jam: When the Bill Bolin tracks were removed, "Shatterface" by Jared "SolusLunes" Micks replaced Bolin's "Strider Showdown", then was replaced with "Derse Dreamers" by Jeremy "Solatrus" Iamurri when Micks' contributions were removed due to a plagiarism controversy.

**Comment by lKomus** [comment]
Oh I see, I didn't know about SolusLunes' music. I'm unsure if this issue should be closed or stay open if one should think that it's better to have Bill Bolin's tracks for new readers or not. I'll let someone else be the judge.

**Comment by GiovanH** [comment]
There are actually three sets of music this flash can use, and the opaque "controversial content" flag for new readers can cycle between at most two options, so unfortunately the bolin music here isn't accessible until after you unlock the comic, currently.
