### ISSUE TITLE
june

### ISSUE THREAD

**Issue by twinkiescereal** [Bambosh/unofficial-homestuck-collection#348]
Hi all i really love the program u made thank u for all your work!! I would really like a feature that replaces john's name with june and updates her pronouns. thanks! holly

**Comment by Niklink** [comment]
This is the kind of thing the new modding system is perfectly suited for, however it requires someone to meticulously go through the entire story to note everything that needs to be replaced. You can't just find and replace because that doesn't account for quirks, gendered language, words in images and in flashes, walkaround dialogue, etc. It's a lot of manual labor.

**Comment by twinkiescereal** [comment]
> 

Thanks for your response im rereading now so i guess i may as well do that haha

**Comment by caseyclosed** [comment]
hi! i've actually been working on a mod of this kind steadily for a couple of weeks now!

**Comment by twinkiescereal** [comment]
Sweet thank u so much !!! Ur going to see heaven for sure
