### ISSUE TITLE
asset pack .zip file appears to be corrupted

### ISSUE THREAD

**Issue by microlith57** [Bambosh/unofficial-homestuck-collection#353]
when i attempt to unzip the asset pack zip obtained from mediafire (the other mirrors are too slow to use for me), the download succeeds but `unzip` (UnZip 6.00 of 20 April 2009, by Debian) fails with the following error:

```
$ unzip "Asset Pack V2 - The Unofficial Homestuck Collection.zip" 
Archive:  Asset Pack V2 - The Unofficial Homestuck Collection.zip
warning [Asset Pack V2 - The Unofficial Homestuck Collection.zip]:  149632511 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Asset Pack V2 - The Unofficial Homestuck Collection.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

i am confident that `unzip` is correct as it has worked on all other archives i have tried; i have also tried other unzipping programs and they also fail.

redownloading the zip also failed with the same message (& same number of extra bytes), leading me to believe this is a problem with the archive rather than my disk.

**Comment by GiovanH** [comment]
Which mirror did you use?

**Comment by microlith57** [comment]
the mediafire one (mirror 1)

**Comment by GiovanH** [comment]
There seems to be a problem extracting the zip with some very old extraction utilities, like the decade-old version of unzip packaged with debian. For now, try extracting it with a standard extraction tool.

**Comment by microlith57** [comment]
i extracted it with `7z`, which appears to have worked (it finished with "Open Errors: 1" but nevertheless extracted at least most of the files), so i'll close this issue.
thanks for the help!

**Comment by GiovanH** [comment]
I'm actually going to leave this open; it's good to have a known working workaround, but we still need to figure out why the archivers are complaining and upload a fresh version!

**Comment by soulwa** [comment]
I also had this issue on EndeavourOS (`5.16.16-arch1-1`). I solved it using `7z`, which extracted all of the files with `Everything is Ok` at the end. This occurred with the archive from the first mirror, and I redownloaded it to verify that no corruption happened due to network issues.
I had the following output with unzip:
```
$ unzip Asset\ Pack\ V2\ -\ The\ Unofficial\ Homestuck\ Collection.zip 
Archive:  Asset Pack V2 - The Unofficial Homestuck Collection.zip
warning [Asset Pack V2 - The Unofficial Homestuck Collection.zip]:  149632511 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Asset Pack V2 - The Unofficial Homestuck Collection.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
and here's the output of `unzip -v`:
```
$ unzip -v
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 11.2.0 for Unix (Linux ELF) on Feb 16 2022.

UnZip special compilation options:
        ACORN_FTYPE_NFS
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        UNICODE_SUPPORT [wide-chars, char coding: UTF-8] (handle UTF-8 paths)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        USE_BZIP2 (PKZIP 4.6+, using bzip2 lib version 1.0.8, 13-Jul-2019)
        VMS_TEXT_CONV
        WILD_STOP_AT_DIR
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```

**Comment by soulwa** [comment]
**Running `zip -FF` on the existing archive should produce one which works with standard Unix `unzip`, and has identical files.** 

As a followup for a potential fix to this issue, which I can also confirm happens with MacOS `unzip`:

I'm not exactly sure what the cause of this is, since running `zip -T` on the archive, which tests the integrity of the zip file, gives the output
```
$ zip -T Asset\ Pack\ V2\ -\ The\ Unofficial\ Homestuck\ Collection.zip 


Could not find:
  Asset Pack V2 - The Unofficial Homestuck Collection.z01

Hit c      (change path to where this split file is)
    q      (abort archive - quit)
 or ENTER  (try reading this split again):
```

but the archive is definitely not split, as it can be extracted completely using other tools. My best guess right now is that the central directory has been corrupted in such a way to make zip tools think there is a split archive.

Regardless of this, the archive can be repaired in such a way that Unix `unzip` tools work using `zip -FF`, which repairs damaged archives. `zip -F` does not work, because the central directory is not mostly intact. Running
```
$ zip -FF Asset\ Pack\ V2\ -\ The\ Unofficial\ Homestuck\ Collection.zip --out fixed.zip
```
gives an archive `fixed.zip`, which contains all the same files as `Asset\ Pack\ V2\ -\ The\ Unofficial\ Homestuck\ Collection.zip`. Furthermore, using `cmp` I was able to verify that the only changes to the file occur at byte offsets used by the zip file either in the central directory (likely repairing the issues with the original archive), or to mark the end of the central directory, meaning the asset files should all be identical. Additionally, `zip -T` confirms that this archive is OK, and unzipping with `unzip` gives the same directory as unzipping the original, "broken" archive with `7z` (and it works!)

The SHA-256 hash of the fixed archive I have is
```
c178c4085d01f07fe366a1154bfd0ec006b71137f707f45dcf07b88379915fe4  fixed.zip
```

I haven't verified that it works with Windows unzip programs, but it works with MacOS/Linux utilities which it didn't before, and I don't think that `zip -FF` would cause any further incompatibilities. I can still test this if it's desired though.

**Comment by microlith57** [comment]
i have now finished chapters 1-7 of homestuck using the `7z`-unzipped archive, and experienced no issues; however, upon loading the first page of problem sleuth the image (`http://127.0.0.1:40177/advimgs/ps/ps001.gif`) did not display, with error
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
indeed, the `advimgs` folder has only four items in it (`ps072.gif`, `ps1520_1.gif`, `ps1521.gif`, and `ps162.gif`), so evidently the archive is damaged.
i will attempt the `zip -FF` technique soon.

**Comment by microlith57** [comment]
using `zip -FF` and merging the resulting directory with my existing assets folder seems to have fixed my install!

**Comment by seine-axelenz** [comment]
Commenting to say this issue still persists, I'm running pop!_OS (ubuntu derivative).
Preinstalled zip tools that have worked for everything else report the archive as damaged, repairing it using `zip -FF` works and the resulting archive can be extracted without issues.
