### ISSUE TITLE
Panel images should be pixelated for high-dpi/zoomed screens

### ISSUE THREAD

**Issue by towerofnix** [Bambosh/unofficial-homestuck-collection#6]
CSS has a property, `image-rendering: pixelated`, for leaving images pixelated when rendered at a higher resolution than source size (i.e. nearest neighbor scaling), which would likely help on high-dpi and zoomed screens. (I've been using it in personal homestuck.com/prequel/etc userstyles for ages!)

Pretty sure the code should go [here](https://github.com/Bambosh/unofficial-homestuck-collection/blob/3d08e32ee46fc78bdef95c5159703110e8ce9f9d/src/components/UIElements/MediaEmbed.vue#L599)! I don't have a system to test on myself, but [here's a report](https://www.reddit.com/r/homestuck/comments/ji7rp6/the_unofficial_homestuck_collection_an_offline/ga6kn58/) of some image blurring (and the only current fix, which is 100% scaling on a normal DPI screen - obviously no good for user experience!).

There's also [`crisp-edges`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering#Values) (under the nonstandard Chrome name `-webkit-optimize-contrast`), which can use other no-blur scaling algorithms and is specifically designed for pixel art; that might be worth testing too.

**Comment by JovialKnoll** [comment]
Related, I think a built in zoom would be very useful, but probably only with the above.

**Comment by Bambosh** [comment]
This is a tricky one - and something I'm not sure there's a clean solution to overall. Currently, regular MSPA pages (as well as a few specific elements) use `image-rendering: pixelated`. People using scaling on high dpi screens are _always_ going to run into problems with this, as long as they're viewing the image at a non-integer multiple of its original size. Even if the image isn't 'blurry', it's mathematically inevitable that the scaled image is gonna look crunchy as all hell.

The current solution I'm working on is to let people choose whether they want to keep nearest neighbour scaling, or if they want to revert to regular ol' blurry scaling. Without a way to be certain how each user's screen is configured, I'm struggling to see a way to give everyone a method to view images at their original scale. 

Quick side note, I did take a look into crisp-edges. While the spec does describe an algorithm like that, it doesn't look like any modern browsers actually _do_ that. In our case, it just reverts back to automatic scaling. While this may be revisited in a future version of Chromium, they stopped supporting the Flash plugin a while ago. This probably isn't something we'll ever be able to fully resolve 😔

Oh, and zooming is already in! The shortcut probably isn't clear enough though, because a lot of people seem to be missing it.

**Comment by Bambosh** [comment]
V1.1.0 includes the scaling mode toggle, so I'm marking this as resolved.
