### ISSUE TITLE
Namco High unlock seems to be in the wrong place

### ISSUE THREAD

**Issue by jseakle** [Bambosh/unofficial-homestuck-collection#72]
I got the unlock announcement at a kind of random time and didn't know why. No newspost mentioning it was available, so I just figured it was some out-of-band thing that wasn't mentioned on MSPA. But now hundreds of pages later I've gotten to the newspost announcement of it.

**Comment by Niklink** [comment]
Yeah, it seems to be set to unlock at EOA6I5 instead of during Gigapause. Possibly to avoid overwhelming the reader with two content-heavy unlocks like Namco High and all of Paradox Space at the same time?

**Comment by jseakle** [comment]
If it is intentional, that seems very silly. I think it's probably just a mistake.

**Comment by Bambosh** [comment]
Yeah, this one was an intentional decision. The beginning of A6A6 is a pretty huge milestone, and also happens to be the point where Namco High becomes totally spoiler-safe for the reader. In general, I ended up prioritizing the reader experience more than strictly adhering to the dates. You'll also notice a few album notifications that don't pop the exact second they unlock, instead triggering at the end of a scene or something.

**Comment by jseakle** [comment]
i found it quite confusing for such a big thing to unlock without any mention in the newsposts.. because the relevant newsposts didn't unlock until later. it really felt like a mistake.
