### ISSUE TITLE
a way to enable the pre-caliborn banner?

### ISSUE THREAD

**Issue by thetntm** [Bambosh/unofficial-homestuck-collection#73]
Originally in homestuck, the MSPA Banner was at the top of the page. However, after Caliborn hits the page with the crowbar, this changed, which is why there are now the faces from the banner at the bottom of the screen on every page. A similar situation happened with the candy corn between the menu bar items, as it was changed after trickster mode. I really appreciate all the retcon options given, but was wondering if it was possible to add an option so that the pages look the same as they originally did.

**Comment by GiovanH** [comment]
There were a few different site layouts, including a lopsided one with a sidebar. The current layout for TUHC is the last one used, and is probably the best choice for archive reading (since a sidebar with recent pages doesn't really apply). 

In theory, layouts could be part of custom CSS themes in the future
